import * as satellite from "satellite.js";
import { propagate, getOrbitalElements } from "@/lib/orbit";

/**
 * Builds a KML LineString ground track for one full orbit, starting now.
 * Pure client-side string generation — no server cost, no dependencies
 * beyond satellite.js (already in the bundle).
 */
export function buildOrbitKml(name: string, line1: string, line2: string): string {
  const satrec = satellite.twoline2satrec(line1, line2);
  let periodMin = 90;
  try {
    periodMin = getOrbitalElements(satrec).periodMin;
  } catch {
    /* keep default */
  }

  const steps = 180;
  const now = Date.now();
  const coords: string[] = [];
  for (let i = 0; i <= steps; i++) {
    const t = new Date(now + (i / steps) * periodMin * 60 * 1000);
    const state = propagate(satrec, t);
    if (!state) continue;
    coords.push(`${state.lon.toFixed(5)},${state.lat.toFixed(5)},${Math.max(0, state.altitudeKm * 1000).toFixed(0)}`);
  }

  const escapedName = name.replace(/&/g, "&amp;").replace(/</g, "&lt;");

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapedName} — orbit track</name>
    <description>Generated by Orbit Watch from public TLE data. One full orbital period starting ${new Date(
      now
    ).toISOString()}.</description>
    <Style id="orbitLine">
      <LineStyle>
        <color>ffeb8a4f</color>
        <width>2</width>
      </LineStyle>
    </Style>
    <Placemark>
      <name>${escapedName}</name>
      <styleUrl>#orbitLine</styleUrl>
      <LineString>
        <altitudeMode>absolute</altitudeMode>
        <coordinates>${coords.join(" ")}</coordinates>
      </LineString>
    </Placemark>
  </Document>
</kml>`;
}

/** Triggers a browser download of the KML — no server round-trip needed. */
export function downloadOrbitKml(name: string, line1: string, line2: string) {
  const kml = buildOrbitKml(name, line1, line2);
  const blob = new Blob([kml], { type: "application/vnd.google-earth.kml+xml" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name.replace(/[^a-z0-9-]+/gi, "_")}-orbit.kml`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
